{{- if .Values.clusterRoleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  name: {{ include "microservice.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "microservice.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "microservice.serviceAccountName" . }}
  namespace: default
{{- end }}