{{- if .Values.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  name: {{ include "microservice.serviceAccountName" . }}
rules:
{{- if .Values.clusterRole.rules }}
{{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end }}
{{- end }}