{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ default "" $value | quote }}
  {{- end }}
{{- end }}

---

{{- if .Values.secretVolume.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret-volume
type: Opaque
stringData:
  {{- range .Values.secretVolume.files }}
  {{ .name }}: |
    {{ .content | nindent 4 }}
  {{- end }}
{{- end }}