{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      {{- if .Values.serviceMonitor.port }}
      port: {{ .Values.serviceMonitor.port }}
      {{- else }}
      targetPort: {{ .Values.serviceMonitor.targetPort | quote }}
      {{- end }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}