apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ if .Values.service.ports.http }}
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
    {{ end }}
    {{ if .Values.service.ports.grpc }}
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.ports.grpc }}
      protocol: TCP
    {{ end }}
    {{ if .Values.service.ports.healthcheck }}
    - name: healthcheck
      port: {{ .Values.service.ports.healthcheck }}
      targetPort: {{ .Values.service.ports.healthcheck }}
      protocol: TCP
    {{ end }}
    {{ if .Values.service.ports.websocket }}
    - name: websocket
      port: {{ .Values.service.ports.websocket }}
      targetPort: {{ .Values.service.ports.websocket }}
      protocol: TCP
    {{ end }}
    {{ if .Values.service.ports.websocket }}
    - name: websocket
      port: {{ .Values.service.ports.websocket }}
      targetPort: {{ .Values.service.ports.websocket }}
      protocol: TCP
    {{ end }}
  selector:
    {{- include "microservice.selectorLabels" . | nindent 4 }}
